apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: rust-instance-2
  name: rust-instance-2
spec:
  ports:
    - name: "3031"
      port: 3031
      targetPort: 3030
  selector:
    io.kompose.service: rust-instance-2
